version: "3.9"

services:
  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile
    networks: 
      - service
    command: ruby tst_httpclient.rb
    volumes:
      - ./client:/app
    ports:      
      - "5678"

  server:
    build: 
      context: ./server/  
      dockerfile: Dockerfile
    networks: 
      - service
    command: ruby sinatra_server.rb
    volumes:
      - ./server:/app
    ports:
        - "5679"

networks:
  service:
    name: service